export type Verb = {
  infinitive: string;
  pastSimple: string;
  pastParticiple: string;
  translation: string;
  type: 'regular' | 'irregular';
};

export const verbs: Verb[] = [
  // Irregular Verbs
  { infinitive: 'arise', pastSimple: 'arose', pastParticiple: 'arisen', translation: 'surgir', type: 'irregular' },
  { infinitive: 'awake', pastSimple: 'awoke', pastParticiple: 'awoken', translation: 'despertar', type: 'irregular' },
  { infinitive: 'be', pastSimple: 'was/were', pastParticiple: 'been', translation: 'ser/estar', type: 'irregular' },
  { infinitive: 'be able', pastSimple: 'was/were able', pastParticiple: 'been able', translation: 'ser capaz/poder', type: 'irregular' },
  { infinitive: 'bear', pastSimple: 'bore', pastParticiple: 'born', translation: 'soportar/dar a luz', type: 'irregular' },
  { infinitive: 'beat', pastSimple: 'beat', pastParticiple: 'beaten', translation: 'golpear', type: 'irregular' },
  { infinitive: 'become', pastSimple: 'became', pastParticiple: 'become', translation: 'convertirse', type: 'irregular' },
  { infinitive: 'begin', pastSimple: 'began', pastParticiple: 'begun', translation: 'empezar', type: 'irregular' },
  { infinitive: 'bend', pastSimple: 'bent', pastParticiple: 'bent', translation: 'doblar', type: 'irregular' },
  { infinitive: 'bet', pastSimple: 'bet', pastParticiple: 'bet', translation: 'apostar', type: 'irregular' },
  { infinitive: 'bid', pastSimple: 'bid', pastParticiple: 'bid', translation: 'pujar', type: 'irregular' },
  { infinitive: 'bind', pastSimple: 'bound', pastParticiple: 'bound', translation: 'atar', type: 'irregular' },
  { infinitive: 'bite', pastSimple: 'bit', pastParticiple: 'bitten', translation: 'morder', type: 'irregular' },
  { infinitive: 'bleed', pastSimple: 'bled', pastParticiple: 'bled', translation: 'sangrar', type: 'irregular' },
  { infinitive: 'blow', pastSimple: 'blew', pastParticiple: 'blown', translation: 'soplar', type: 'irregular' },
  { infinitive: 'break', pastSimple: 'broke', pastParticiple: 'broken', translation: 'romper', type: 'irregular' },
  { infinitive: 'breed', pastSimple: 'bred', pastParticiple: 'bred', translation: 'criar', type: 'irregular' },
  { infinitive: 'bring', pastSimple: 'brought', pastParticiple: 'brought', translation: 'traer', type: 'irregular' },
  { infinitive: 'broadcast', pastSimple: 'broadcast', pastParticiple: 'broadcast', translation: 'emitir', type: 'irregular' },
  { infinitive: 'build', pastSimple: 'built', pastParticiple: 'built', translation: 'construir', type: 'irregular' },
  { infinitive: 'burn', pastSimple: 'burnt/burned', pastParticiple: 'burnt/burned', translation: 'quemar', type: 'irregular' },
  { infinitive: 'burst', pastSimple: 'burst', pastParticiple: 'burst', translation: 'reventar', type: 'irregular' },
  { infinitive: 'buy', pastSimple: 'bought', pastParticiple: 'bought', translation: 'comprar', type: 'irregular' },
  { infinitive: 'can', pastSimple: 'could', pastParticiple: 'been able', translation: 'poder', type: 'irregular' },
  { infinitive: 'cast', pastSimple: 'cast', pastParticiple: 'cast', translation: 'lanzar', type: 'irregular' },
  { infinitive: 'catch', pastSimple: 'caught', pastParticiple: 'caught', translation: 'atrapar', type: 'irregular' },
  { infinitive: 'choose', pastSimple: 'chose', pastParticiple: 'chosen', translation: 'elegir', type: 'irregular' },
  { infinitive: 'cling', pastSimple: 'clung', pastParticiple: 'clung', translation: 'aferrarse', type: 'irregular' },
  { infinitive: 'come', pastSimple: 'came', pastParticiple: 'come', translation: 'venir', type: 'irregular' },
  { infinitive: 'cost', pastSimple: 'cost', pastParticiple: 'cost', translation: 'costar', type: 'irregular' },
  { infinitive: 'creep', pastSimple: 'crept', pastParticiple: 'crept', translation: 'arrastrarse', type: 'irregular' },
  { infinitive: 'cut', pastSimple: 'cut', pastParticiple: 'cut', translation: 'cortar', type: 'irregular' },
  { infinitive: 'deal', pastSimple: 'dealt', pastParticiple: 'dealt', translation: 'tratar', type: 'irregular' },
  { infinitive: 'dig', pastSimple: 'dug', pastParticiple: 'dug', translation: 'cavar', type: 'irregular' },
  { infinitive: 'do', pastSimple: 'did', pastParticiple: 'done', translation: 'hacer', type: 'irregular' },
  { infinitive: 'draw', pastSimple: 'drew', pastParticiple: 'drawn', translation: 'dibujar', type: 'irregular' },
  { infinitive: 'dream', pastSimple: 'dreamt/dreamed', pastParticiple: 'dreamt/dreamed', translation: 'soñar', type: 'irregular' },
  { infinitive: 'drink', pastSimple: 'drank', pastParticiple: 'drunk', translation: 'beber', type: 'irregular' },
  { infinitive: 'drive', pastSimple: 'drove', pastParticiple: 'driven', translation: 'conducir', type: 'irregular' },
  { infinitive: 'eat', pastSimple: 'ate', pastParticiple: 'eaten', translation: 'comer', type: 'irregular' },
  { infinitive: 'fall', pastSimple: 'fell', pastParticiple: 'fallen', translation: 'caer', type: 'irregular' },
  { infinitive: 'feed', pastSimple: 'fed', pastParticiple: 'fed', translation: 'alimentar', type: 'irregular' },
  { infinitive: 'feel', pastSimple: 'felt', pastParticiple: 'felt', translation: 'sentir', type: 'irregular' },
  { infinitive: 'fight', pastSimple: 'fought', pastParticiple: 'fought', translation: 'luchar', type: 'irregular' },
  { infinitive: 'find', pastSimple: 'found', pastParticiple: 'found', translation: 'encontrar', type: 'irregular' },
  { infinitive: 'flee', pastSimple: 'fled', pastParticiple: 'fled', translation: 'huir', type: 'irregular' },
  { infinitive: 'fly', pastSimple: 'flew', pastParticiple: 'flown', translation: 'volar', type: 'irregular' },
  { infinitive: 'forbid', pastSimple: 'forbade', pastParticiple: 'forbidden', translation: 'prohibir', type: 'irregular' },
  { infinitive: 'forget', pastSimple: 'forgot', pastParticiple: 'forgotten', translation: 'olvidar', type: 'irregular' },
  { infinitive: 'forgive', pastSimple: 'forgave', pastParticiple: 'forgiven', translation: 'perdonar', type: 'irregular' },
  { infinitive: 'freeze', pastSimple: 'froze', pastParticiple: 'frozen', translation: 'congelar', type: 'irregular' },
  { infinitive: 'get', pastSimple: 'got', pastParticiple: 'got/gotten', translation: 'obtener', type: 'irregular' },
  { infinitive: 'get up', pastSimple: 'got up', pastParticiple: 'gotten up', translation: 'levantarse', type: 'irregular' },
  { infinitive: 'give', pastSimple: 'gave', pastParticiple: 'given', translation: 'dar', type: 'irregular' },
  { infinitive: 'go', pastSimple: 'went', pastParticiple: 'gone', translation: 'ir', type: 'irregular' },
  { infinitive: 'grind', pastSimple: 'ground', pastParticiple: 'ground', translation: 'moler', type: 'irregular' },
  { infinitive: 'grow', pastSimple: 'grew', pastParticiple: 'grown', translation: 'crecer', type: 'irregular' },
  { infinitive: 'hang', pastSimple: 'hung', pastParticiple: 'hung', translation: 'colgar', type: 'irregular' },
  { infinitive: 'have', pastSimple: 'had', pastParticiple: 'had', translation: 'tener/haber', type: 'irregular' },
  { infinitive: 'have to', pastSimple: 'had to', pastParticiple: 'had to', translation: 'deber/tener que', type: 'irregular' },
  { infinitive: 'hear', pastSimple: 'heard', pastParticiple: 'heard', translation: 'oír', type: 'irregular' },
  { infinitive: 'hide', pastSimple: 'hid', pastParticiple: 'hidden', translation: 'esconder', type: 'irregular' },
  { infinitive: 'hit', pastSimple: 'hit', pastParticiple: 'hit', translation: 'golpear', type: 'irregular' },
  { infinitive: 'hold', pastSimple: 'held', pastParticiple: 'held', translation: 'sostener', type: 'irregular' },
  { infinitive: 'hurt', pastSimple: 'hurt', pastParticiple: 'hurt', translation: 'herir/dañar', type: 'irregular' },
  { infinitive: 'keep', pastSimple: 'kept', pastParticiple: 'kept', translation: 'mantener/guardar', type: 'irregular' },
  { infinitive: 'kneel', pastSimple: 'knelt', pastParticiple: 'knelt', translation: 'arrodillarse', type: 'irregular' },
  { infinitive: 'knit', pastSimple: 'knit/knitted', pastParticiple: 'knit/knitted', translation: 'tejer', type: 'irregular' },
  { infinitive: 'know', pastSimple: 'knew', pastParticiple: 'known', translation: 'saber/conocer', type: 'irregular' },
  { infinitive: 'lay', pastSimple: 'laid', pastParticiple: 'laid', translation: 'poner/colocar', type: 'irregular' },
  { infinitive: 'lead', pastSimple: 'led', pastParticiple: 'led', translation: 'guiar/conducir', type: 'irregular' },
  { infinitive: 'lean', pastSimple: 'leant/leaned', pastParticiple: 'leant/leaned', translation: 'apoyarse', type: 'irregular' },
  { infinitive: 'leave', pastSimple: 'left', pastParticiple: 'left', translation: 'salir/dejar', type: 'irregular' },
  { infinitive: 'lend', pastSimple: 'lent', pastParticiple: 'lent', translation: 'prestar', type: 'irregular' },
  { infinitive: 'let', pastSimple: 'let', pastParticiple: 'let', translation: 'permitir', type: 'irregular' },
  { infinitive: 'lie', pastSimple: 'lay', pastParticiple: 'lain', translation: 'yacer/tumbarse', type: 'irregular' },
  { infinitive: 'light', pastSimple: 'lit/lighted', pastParticiple: 'lit/lighted', translation: 'prender/iluminar', type: 'irregular' },
  { infinitive: 'lose', pastSimple: 'lost', pastParticiple: 'lost', translation: 'perder', type: 'irregular' },
  { infinitive: 'make', pastSimple: 'made', pastParticiple: 'made', translation: 'hacer/fabricar', type: 'irregular' },
  { infinitive: 'mean', pastSimple: 'meant', pastParticiple: 'meant', translation: 'significar', type: 'irregular' },
  { infinitive: 'meet', pastSimple: 'met', pastParticiple: 'met', translation: 'conocer/encontrarse', type: 'irregular' },
  { infinitive: 'mistake', pastSimple: 'mistook', pastParticiple: 'mistaken', translation: 'equivocarse', type: 'irregular' },
  { infinitive: 'overcome', pastSimple: 'overcame', pastParticiple: 'overcome', translation: 'superar', type: 'irregular' },
  { infinitive: 'pay', pastSimple: 'paid', pastParticiple: 'paid', translation: 'pagar', type: 'irregular' },
  { infinitive: 'put', pastSimple: 'put', pastParticiple: 'put', translation: 'poner', type: 'irregular' },
  { infinitive: 'read', pastSimple: 'read', pastParticiple: 'read', translation: 'leer', type: 'irregular' },
  { infinitive: 'ride', pastSimple: 'rode', pastParticiple: 'ridden', translation: 'montar', type: 'irregular' },
  { infinitive: 'ring', pastSimple: 'rang', pastParticiple: 'rung', translation: 'sonar', type: 'irregular' },
  { infinitive: 'rise', pastSimple: 'rose', pastParticiple: 'risen', translation: 'elevarse', type: 'irregular' },
  { infinitive: 'run', pastSimple: 'ran', pastParticiple: 'run', translation: 'correr', type: 'irregular' },
  { infinitive: 'say', pastSimple: 'said', pastParticiple: 'said', translation: 'decir', type: 'irregular' },
  { infinitive: 'see', pastSimple: 'saw', pastParticiple: 'seen', translation: 'ver', type: 'irregular' },
  { infinitive: 'seek', pastSimple: 'sought', pastParticiple: 'sought', translation: 'buscar', type: 'irregular' },
  { infinitive: 'sell', pastSimple: 'sold', pastParticiple: 'sold', translation: 'vender', type: 'irregular' },
  { infinitive: 'send', pastSimple: 'sent', pastParticiple: 'sent', translation: 'enviar', type: 'irregular' },
  { infinitive: 'set', pastSimple: 'set', pastParticiple: 'set', translation: 'establecer', type: 'irregular' },
  { infinitive: 'sew', pastSimple: 'sewed', pastParticiple: 'sewn/sewed', translation: 'coser', type: 'irregular' },
  { infinitive: 'shake', pastSimple: 'shook', pastParticiple: 'shaken', translation: 'agitar', type: 'irregular' },
  { infinitive: 'shear', pastSimple: 'shore/sheared', pastParticiple: 'shorn/sheared', translation: 'esquilar', type: 'irregular' },
  { infinitive: 'shine', pastSimple: 'shone', pastParticiple: 'shone', translation: 'brillar', type: 'irregular' },
  { infinitive: 'shoot', pastSimple: 'shot', pastParticiple: 'shot', translation: 'disparar', type: 'irregular' },
  { infinitive: 'show', pastSimple: 'showed', pastParticiple: 'shown/showed', translation: 'mostrar', type: 'irregular' },
  { infinitive: 'shrink', pastSimple: 'shrank', pastParticiple: 'shrunk', translation: 'encoger', type: 'irregular' },
  { infinitive: 'shut', pastSimple: 'shut', pastParticiple: 'shut', translation: 'cerrar', type: 'irregular' },
  { infinitive: 'sing', pastSimple: 'sang', pastParticiple: 'sung', translation: 'cantar', type: 'irregular' },
  { infinitive: 'sink', pastSimple: 'sank', pastParticiple: 'sunk', translation: 'hundir', type: 'irregular' },
  { infinitive: 'sit', pastSimple: 'sat', pastParticiple: 'sat', translation: 'sentarse', type: 'irregular' },
  { infinitive: 'sleep', pastSimple: 'slept', pastParticiple: 'slept', translation: 'dormir', type: 'irregular' },
  { infinitive: 'slide', pastSimple: 'slid', pastParticiple: 'slid', translation: 'deslizar', type: 'irregular' },
  { infinitive: 'smell', pastSimple: 'smelt/smelled', pastParticiple: 'smelt/smelled', translation: 'oler', type: 'irregular' },
  { infinitive: 'sow', pastSimple: 'sowed', pastParticiple: 'sown/sowed', translation: 'sembrar', type: 'irregular' },
  { infinitive: 'speak', pastSimple: 'spoke', pastParticiple: 'spoken', translation: 'hablar', type: 'irregular' },
  { infinitive: 'speed', pastSimple: 'sped/speeded', pastParticiple: 'sped/speeded', translation: 'acelerar', type: 'irregular' },
  { infinitive: 'spell', pastSimple: 'spelt/spelled', pastParticiple: 'spelt/spelled', translation: 'deletrear', type: 'irregular' },
  { infinitive: 'spend', pastSimple: 'spent', pastParticiple: 'spent', translation: 'gastar', type: 'irregular' },
  { infinitive: 'spill', pastSimple: 'spilt/spilled', pastParticiple: 'spilt/spilled', translation: 'derramar', type: 'irregular' },
  { infinitive: 'spin', pastSimple: 'spun', pastParticiple: 'spun', translation: 'girar', type: 'irregular' },
  { infinitive: 'spit', pastSimple: 'spat', pastParticiple: 'spat', translation: 'escupir', type: 'irregular' },
  { infinitive: 'split', pastSimple: 'split', pastParticiple: 'split', translation: 'dividir', type: 'irregular' },
  { infinitive: 'spoil', pastSimple: 'spoilt/spoiled', pastParticiple: 'spoilt/spoiled', translation: 'estropear', type: 'irregular' },
  { infinitive: 'spread', pastSimple: 'spread', pastParticiple: 'spread', translation: 'extender', type: 'irregular' },
  { infinitive: 'spring', pastSimple: 'sprang', pastParticiple: 'sprung', translation: 'saltar', type: 'irregular' },
  { infinitive: 'stand', pastSimple: 'stood', pastParticiple: 'stood', translation: 'estar de pie', type: 'irregular' },
  { infinitive: 'steal', pastSimple: 'stole', pastParticiple: 'stolen', translation: 'robar', type: 'irregular' },
  { infinitive: 'stick', pastSimple: 'stuck', pastParticiple: 'stuck', translation: 'pegar', type: 'irregular' },
  { infinitive: 'sting', pastSimple: 'stung', pastParticiple: 'stung', translation: 'picar', type: 'irregular' },
  { infinitive: 'stink', pastSimple: 'stank', pastParticiple: 'stunk', translation: 'apestar', type: 'irregular' },
  { infinitive: 'stride', pastSimple: 'strode', pastParticiple: 'stridden', translation: 'dar zancadas', type: 'irregular' },
  { infinitive: 'strike', pastSimple: 'struck', pastParticiple: 'struck/stricken', translation: 'golpear', type: 'irregular' },
  { infinitive: 'swear', pastSimple: 'swore', pastParticiple: 'sworn', translation: 'jurar', type: 'irregular' },
  { infinitive: 'sweat', pastSimple: 'sweat/sweated', pastParticiple: 'sweat/sweated', translation: 'sudar', type: 'irregular' },
  { infinitive: 'sweep', pastSimple: 'swept', pastParticiple: 'swept', translation: 'barrer', type: 'irregular' },
  { infinitive: 'swell', pastSimple: 'swelled', pastParticiple: 'swollen/swelled', translation: 'hincharse', type: 'irregular' },
  { infinitive: 'swim', pastSimple: 'swam', pastParticiple: 'swum', translation: 'nadar', type: 'irregular' },
  { infinitive: 'swing', pastSimple: 'swung', pastParticiple: 'swung', translation: 'balancearse', type: 'irregular' },
  { infinitive: 'take', pastSimple: 'took', pastParticiple: 'taken', translation: 'tomar', type: 'irregular' },
  { infinitive: 'teach', pastSimple: 'taught', pastParticiple: 'taught', translation: 'enseñar', type: 'irregular' },
  { infinitive: 'tear', pastSimple: 'tore', pastParticiple: 'torn', translation: 'rasgar', type: 'irregular' },
  { infinitive: 'tell', pastSimple: 'told', pastParticiple: 'told', translation: 'decir', type: 'irregular' },
  { infinitive: 'think', pastSimple: 'thought', pastParticiple: 'thought', translation: 'pensar', type: 'irregular' },
  { infinitive: 'throw', pastSimple: 'threw', pastParticiple: 'thrown', translation: 'lanzar', type: 'irregular' },
  { infinitive: 'thrust', pastSimple: 'thrust', pastParticiple: 'thrust', translation: 'empujar', type: 'irregular' },
  { infinitive: 'tread', pastSimple: 'trod', pastParticiple: 'trodden', translation: 'pisar', type: 'irregular' },
  { infinitive: 'undergo', pastSimple: 'underwent', pastParticiple: 'undergone', translation: 'someterse a', type: 'irregular' },
  { infinitive: 'understand', pastSimple: 'understood', pastParticiple: 'understood', translation: 'entender', type: 'irregular' },
  { infinitive: 'undertake', pastSimple: 'undertook', pastParticiple: 'undertaken', translation: 'emprender', type: 'irregular' },
  { infinitive: 'wake', pastSimple: 'woke', pastParticiple: 'woken', translation: 'despertar', type: 'irregular' },
  { infinitive: 'wear', pastSimple: 'wore', pastParticiple: 'worn', translation: 'llevar puesto', type: 'irregular' },
  { infinitive: 'weave', pastSimple: 'wove', pastParticiple: 'woven', translation: 'tejer', type: 'irregular' },
  { infinitive: 'weep', pastSimple: 'wept', pastParticiple: 'wept', translation: 'llorar', type: 'irregular' },
  { infinitive: 'wet', pastSimple: 'wet/wetted', pastParticiple: 'wet/wetted', translation: 'mojar', type: 'irregular' },
  { infinitive: 'win', pastSimple: 'won', pastParticiple: 'won', translation: 'ganar', type: 'irregular' },
  { infinitive: 'wind', pastSimple: 'wound', pastParticiple: 'wound', translation: 'enrollar/dar cuerda', type: 'irregular' },
  { infinitive: 'withdraw', pastSimple: 'withdrew', pastParticiple: 'withdrawn', translation: 'retirar', type: 'irregular' },
  { infinitive: 'wring', pastSimple: 'wrung', pastParticiple: 'wrung', translation: 'estrujar', type: 'irregular' },
  { infinitive: 'write', pastSimple: 'wrote', pastParticiple: 'written', translation: 'escribir', type: 'irregular' },

  // Regular Verbs
  { infinitive: 'accept', pastSimple: 'accepted', pastParticiple: 'accepted', translation: 'aceptar', type: 'regular' },
  { infinitive: 'add', pastSimple: 'added', pastParticiple: 'added', translation: 'añadir', type: 'regular' },
  { infinitive: 'agree', pastSimple: 'agreed', pastParticiple: 'agreed', translation: 'estar de acuerdo', type: 'regular' },
  { infinitive: 'answer', pastSimple: 'answered', pastParticiple: 'answered', translation: 'responder', type: 'regular' },
  { infinitive: 'appear', pastSimple: 'appeared', pastParticiple: 'appeared', translation: 'aparecer', type: 'regular' },
  { infinitive: 'arrive', pastSimple: 'arrived', pastParticiple: 'arrived', translation: 'llegar', type: 'regular' },
  { infinitive: 'ask', pastSimple: 'asked', pastParticiple: 'asked', translation: 'preguntar', type: 'regular' },
  { infinitive: 'believe', pastSimple: 'believed', pastParticiple: 'believed', translation: 'creer', type: 'regular' },
  { infinitive: 'belong', pastSimple: 'belonged', pastParticiple: 'belonged', translation: 'pertenecer', type: 'regular' },
  { infinitive: 'borrow', pastSimple: 'borrowed', pastParticiple: 'borrowed', translation: 'pedir prestado', type: 'regular' },
  { infinitive: 'call', pastSimple: 'called', pastParticiple: 'called', translation: 'llamar', type: 'regular' },
  { infinitive: 'cancel', pastSimple: 'cancelled', pastParticiple: 'cancelled', translation: 'cancelar', type: 'regular' },
  { infinitive: 'change', pastSimple: 'changed', pastParticiple: 'changed', translation: 'cambiar', type: 'regular' },
  { infinitive: 'clean', pastSimple: 'cleaned', pastParticiple: 'cleaned', translation: 'limpiar', type: 'regular' },
  { infinitive: 'climb', pastSimple: 'climbed', pastParticiple: 'climbed', translation: 'escalar', type: 'regular' },
  { infinitive: 'close', pastSimple: 'closed', pastParticiple: 'closed', translation: 'cerrar', type: 'regular' },
  { infinitive: 'compare', pastSimple: 'compared', pastParticiple: 'compared', translation: 'comparar', type: 'regular' },
  { infinitive: 'complain', pastSimple: 'complained', pastParticiple: 'complained', translation: 'quejarse', type: 'regular' },
  { infinitive: 'consider', pastSimple: 'considered', pastParticiple: 'considered', translation: 'considerar', type: 'regular' },
  { infinitive: 'continue', pastSimple: 'continued', pastParticiple: 'continued', translation: 'continuar', type: 'regular' },
  { infinitive: 'cook', pastSimple: 'cooked', pastParticiple: 'cooked', translation: 'cocinar', type: 'regular' },
  { infinitive: 'count', pastSimple: 'counted', pastParticiple: 'counted', translation: 'contar', type: 'regular' },
  { infinitive: 'dance', pastSimple: 'danced', pastParticiple: 'danced', translation: 'bailar', type: 'regular' },
  { infinitive: 'dare', pastSimple: 'dared', pastParticiple: 'dared', translation: 'atreverse', type: 'regular' },
  { infinitive: 'date', pastSimple: 'dated', pastParticiple: 'dated', translation: 'citar/datar', type: 'regular' },
  { infinitive: 'decide', pastSimple: 'decided', pastParticiple: 'decided', translation: 'decidir', type: 'regular' },
  { infinitive: 'deliver', pastSimple: 'delivered', pastParticiple: 'delivered', translation: 'entregar', type: 'regular' },
  { infinitive: 'depend', pastSimple: 'depended', pastParticiple: 'depended', translation: 'depender', type: 'regular' },
  { infinitive: 'describe', pastSimple: 'described', pastParticiple: 'described', translation: 'describir', type: 'regular' },
  { infinitive: 'develop', pastSimple: 'developed', pastParticiple: 'developed', translation: 'desarrollar', type: 'regular' },
  { infinitive: 'disagree', pastSimple: 'disagreed', pastParticiple: 'disagreed', translation: 'En desacuerdo', type: 'regular' },
  { infinitive: 'discover', pastSimple: 'discovered', pastParticiple: 'discovered', translation: 'descubrir', type: 'regular' },
  { infinitive: 'dress', pastSimple: 'dressed', pastParticiple: 'dressed', translation: 'vestir', type: 'regular' },
  { infinitive: 'earn', pastSimple: 'earned', pastParticiple: 'earned', translation: 'ganar (Dinero)', type: 'regular' },
  { infinitive: 'end', pastSimple: 'ended', pastParticiple: 'ended', translation: 'terminar', type: 'regular' },
  { infinitive: 'enjoy', pastSimple: 'enjoyed', pastParticiple: 'enjoyed', translation: 'disfrutar', type: 'regular' },
  { infinitive: 'enter', pastSimple: 'entered', pastParticiple: 'entered', translation: 'entrar', type: 'regular' },
  { infinitive: 'erase', pastSimple: 'erased', pastParticiple: 'erased', translation: 'borrar', type: 'regular' },
  { infinitive: 'expect', pastSimple: 'expected', pastParticiple: 'expected', translation: 'esperar/suponer', type: 'regular' },
  { infinitive: 'expect', pastSimple: 'expected', pastParticiple: 'expected', translation: 'esperar/suponer', type: 'regular' },
  { infinitive: 'explain', pastSimple: 'explained', pastParticiple: 'explained', translation: 'explicar', type: 'regular' },
  { infinitive: 'fill', pastSimple: 'filled', pastParticiple: 'filled', translation: 'llenar', type: 'regular' },
  { infinitive: 'finish', pastSimple: 'finished', pastParticiple: 'finished', translation: 'terminar', type: 'regular' },
  { infinitive: 'follow', pastSimple: 'followed', pastParticiple: 'followed', translation: 'seguir', type: 'regular' },
  { infinitive: 'happen', pastSimple: 'happened', pastParticiple: 'happened', translation: 'suceder', type: 'regular' },
  { infinitive: 'help', pastSimple: 'helped', pastParticiple: 'helped', translation: 'ayudar', type: 'regular' },
  { infinitive: 'hope', pastSimple: 'hoped', pastParticiple: 'hoped', translation: 'Tener esperanza', type: 'regular' },
  { infinitive: 'hurry', pastSimple: 'hurried', pastParticiple: 'hurried', translation: 'apurarse', type: 'regular' },
  { infinitive: 'imagine', pastSimple: 'imagined', pastParticiple: 'imagined', translation: 'imaginar', type: 'regular' },
  { infinitive: 'include', pastSimple: 'included', pastParticiple: 'included', translation: 'incluir', type: 'regular' },
  { infinitive: 'intend', pastSimple: 'intended', pastParticiple: 'intended', translation: 'tener la intención', type: 'regular' },
  { infinitive: 'introduce', pastSimple: 'introduced', pastParticiple: 'introduced', translation: 'introducir/presentar', type: 'regular' },
  { infinitive: 'invite', pastSimple: 'invited', pastParticiple: 'invited', translation: 'invitar', type: 'regular' },
  { infinitive: 'join', pastSimple: 'joined', pastParticiple: 'joined', translation: 'unirse', type: 'regular' },
  { infinitive: 'jump', pastSimple: 'jumped', pastParticiple: 'jumped', translation: 'saltar', type: 'regular' },
  { infinitive: 'learn', pastSimple: 'learnt/learned', pastParticiple: 'learnt/learned', translation: 'aprender', type: 'regular' },
  { infinitive: 'like', pastSimple: 'liked', pastParticiple: 'liked', translation: 'gustar', type: 'regular' },
  { infinitive: 'listen', pastSimple: 'listened', pastParticiple: 'listened', translation: 'escuchar', type: 'regular' },
  { infinitive: 'live', pastSimple: 'lived', pastParticiple: 'lived', translation: 'vivir', type: 'regular' },
  { infinitive: 'look', pastSimple: 'looked', pastParticiple: 'looked', translation: 'mirar', type: 'regular' },
  { infinitive: 'love', pastSimple: 'loved', pastParticiple: 'loved', translation: 'amar', type: 'regular' },
  { infinitive: 'manage', pastSimple: 'managed', pastParticiple: 'managed', translation: 'manejar/gestionar', type: 'regular' },
  { infinitive: 'mention', pastSimple: 'mentioned', pastParticiple: 'mentioned', translation: 'mencionar', type: 'regular' },
  { infinitive: 'miss', pastSimple: 'missed', pastParticiple: 'missed', translation: 'extrañar/perder', type: 'regular' },
  { infinitive: 'move', pastSimple: 'moved', pastParticiple: 'moved', translation: 'mover/mudarse', type: 'regular' },
  { infinitive: 'name', pastSimple: 'named', pastParticiple: 'named', translation: 'nombrar', type: 'regular' },
  { infinitive: 'need', pastSimple: 'needed', pastParticiple: 'needed', translation: 'necesitar', type: 'regular' },
  { infinitive: 'notice', pastSimple: 'noticed', pastParticiple: 'noticed', translation: 'notar', type: 'regular' },
  { infinitive: 'offer', pastSimple: 'offered', pastParticiple: 'offered', translation: 'ofrecer', type: 'regular' },
  { infinitive: 'open', pastSimple: 'opened', pastParticiple: 'opened', translation: 'abrir', type: 'regular' },
  { infinitive: 'order', pastSimple: 'ordered', pastParticiple: 'ordered', translation: 'ordenar', type: 'regular' },
  { infinitive: 'organize', pastSimple: 'organized', pastParticiple: 'organized', translation: 'organizar', type: 'regular' },
  { infinitive: 'own', pastSimple: 'owned', pastParticiple: 'owned', translation: 'poseer', type: 'regular' },
  { infinitive: 'pack', pastSimple: 'packed', pastParticiple: 'packed', translation: 'empacar', type: 'regular' },
  { infinitive: 'paint', pastSimple: 'painted', pastParticiple: 'painted', translation: 'pintar', type: 'regular' },
  { infinitive: 'pass', pastSimple: 'passed', pastParticiple: 'passed', translation: 'pasar', type: 'regular' },
  { infinitive: 'pick', pastSimple: 'picked', pastParticiple: 'picked', translation: 'recoger', type: 'regular' },
  { infinitive: 'plan', pastSimple: 'planned', pastParticiple: 'planned', translation: 'planear', type: 'regular' },
  { infinitive: 'plant', pastSimple: 'planted', pastParticiple: 'planted', translation: 'plantar', type: 'regular' },
  { infinitive: 'play', pastSimple: 'played', pastParticiple: 'played', translation: 'jugar', type: 'regular' },
  { infinitive: 'point', pastSimple: 'pointed', pastParticiple: 'pointed', translation: 'señalar', type: 'regular' },
  { infinitive: 'practice', pastSimple: 'practiced', pastParticiple: 'practiced', translation: 'practicar', type: 'regular' },
  { infinitive: 'prefer', pastSimple: 'preferred', pastParticiple: 'preferred', translation: 'preferir', type: 'regular' },
  { infinitive: 'prepare', pastSimple: 'prepared', pastParticiple: 'prepared', translation: 'preparar', type: 'regular' },
  { infinitive: 'present', pastSimple: 'presented', pastParticiple: 'presented', translation: 'presentar', type: 'regular' },
  { infinitive: 'print', pastSimple: 'printed', pastParticiple: 'printed', translation: 'imprimir', type: 'regular' },
  { infinitive: 'promise', pastSimple: 'promised', pastParticiple: 'promised', translation: 'prometer', type: 'regular' },
  { infinitive: 'protect', pastSimple: 'protected', pastParticiple: 'protected', translation: 'proteger', type: 'regular' },
  { infinitive: 'provide', pastSimple: 'provided', pastParticiple: 'provided', translation: 'proveer', type: 'regular' },
  { infinitive: 'publish', pastSimple: 'published', pastParticiple: 'published', translation: 'publicar', type: 'regular' },
  { infinitive: 'pull', pastSimple: 'pulled', pastParticiple: 'pulled', translation: 'tirar', type: 'regular' },
  { infinitive: 'punish', pastSimple: 'punished', pastParticiple: 'punished', translation: 'castigar', type: 'regular' },
  { infinitive: 'purify', pastSimple: 'purified', pastParticiple: 'purified', translation: 'purificar', type: 'regular' },
  { infinitive: 'push', pastSimple: 'pushed', pastParticiple: 'pushed', translation: 'empujar', type: 'regular' },
  { infinitive: 'rain', pastSimple: 'rained', pastParticiple: 'rained', translation: 'llover', type: 'regular' },
  { infinitive: 'realize', pastSimple: 'realized', pastParticiple: 'realized', translation: 'darse cuenta', type: 'regular' },
  { infinitive: 'receive', pastSimple: 'received', pastParticiple: 'received', translation: 'recibir', type: 'regular' },
  { infinitive: 'recommend', pastSimple: 'recommended', pastParticiple: 'recommended', translation: 'recomendar', type: 'regular' },
  { infinitive: 'reduce', pastSimple: 'reduced', pastParticiple: 'reduced', translation: 'reducir', type: 'regular' },
  { infinitive: 'relax', pastSimple: 'relaxed', pastParticiple: 'relaxed', translation: 'relajarse', type: 'regular' },
  { infinitive: 'remember', pastSimple: 'remembered', pastParticiple: 'remembered', translation: 'recordar', type: 'regular' },
  { infinitive: 'rent', pastSimple: 'rented', pastParticiple: 'rented', translation: 'alquilar', type: 'regular' },
  { infinitive: 'repeat', pastSimple: 'repeated', pastParticiple: 'repeated', translation: 'repetir', type: 'regular' },
  { infinitive: 'reply', pastSimple: 'replied', pastParticiple: 'replied', translation: 'responder', type: 'regular' },
  { infinitive: 'resist', pastSimple: 'resisted', pastParticiple: 'resisted', translation: 'resistir', type: 'regular' },
  { infinitive: 'return', pastSimple: 'returned', pastParticiple: 'returned', translation: 'volver/devolver', type: 'regular' },
  { infinitive: 'save', pastSimple: 'saved', pastParticiple: 'saved', translation: 'guardar/salvar', type: 'regular' },
  { infinitive: 'search', pastSimple: 'searched', pastParticiple: 'searched', translation: 'buscar', type: 'regular' },
  { infinitive: 'seem', pastSimple: 'seemed', pastParticiple: 'seemed', translation: 'parecer', type: 'regular' },
  { infinitive: 'serve', pastSimple: 'served', pastParticiple: 'served', translation: 'servir', type: 'regular' },
  { infinitive: 'share', pastSimple: 'shared', pastParticiple: 'shared', translation: 'compartir', type: 'regular' },
  { infinitive: 'shop', pastSimple: 'shopped', pastParticiple: 'shopped', translation: 'comprar', type: 'regular' },
  { infinitive: 'shout', pastSimple: 'shouted', pastParticiple: 'shouted', translation: 'gritar', type: 'regular' },
  { infinitive: 'sign', pastSimple: 'signed', pastParticiple: 'signed', translation: 'firmar', type: 'regular' },
  { infinitive: 'smile', pastSimple: 'smiled', pastParticiple: 'smiled', translation: 'sonreir', type: 'regular' },
  { infinitive: 'smoke', pastSimple: 'smoked', pastParticiple: 'smoked', translation: 'fumar', type: 'regular' },
  { infinitive: 'snow', pastSimple: 'snowed', pastParticiple: 'snowed', translation: 'nevar', type: 'regular' },
  { infinitive: 'sound', pastSimple: 'sounded', pastParticiple: 'sounded', translation: 'sonar', type: 'regular' },
  { infinitive: 'start', pastSimple: 'started', pastParticiple: 'started', translation: 'comenzar/iniciar', type: 'regular' },
  { infinitive: 'stay', pastSimple: 'stayed', pastParticiple: 'stayed', translation: 'quedarse/permanecer', type: 'regular' },
  { infinitive: 'step', pastSimple: 'stepped', pastParticiple: 'stepped', translation: 'dar pasos', type: 'regular' },
  { infinitive: 'stop', pastSimple: 'stopped', pastParticiple: 'stopped', translation: 'parar/detenerse', type: 'regular' },
  { infinitive: 'study', pastSimple: 'studied', pastParticiple: 'studied', translation: 'estudiar', type: 'regular' },
  { infinitive: 'surprise', pastSimple: 'surprised', pastParticiple: 'surprised', translation: 'sorprenderse', type: 'regular' },
  { infinitive: 'talk', pastSimple: 'talked', pastParticiple: 'talked', translation: 'conversar', type: 'regular' },
  { infinitive: 'thank', pastSimple: 'thanked', pastParticiple: 'thanked', translation: 'agradecer', type: 'regular' },
  { infinitive: 'touch', pastSimple: 'touched', pastParticiple: 'touched', translation: 'tocar', type: 'regular' },
  { infinitive: 'trade', pastSimple: 'traded', pastParticiple: 'traded', translation: 'comercializar', type: 'regular' },
  { infinitive: 'travel', pastSimple: 'traveled', pastParticiple: 'traveled', translation: 'viajar', type: 'regular' },
  { infinitive: 'treat', pastSimple: 'treated', pastParticiple: 'treated', translation: 'tratar (personas)', type: 'regular' },
  { infinitive: 'try', pastSimple: 'tried', pastParticiple: 'tried', translation: 'intentar', type: 'regular' },
  { infinitive: 'turn', pastSimple: 'turned', pastParticiple: 'turned', translation: 'girar', type: 'regular' },
  { infinitive: 'use', pastSimple: 'used', pastParticiple: 'used', translation: 'usar', type: 'regular' },
  { infinitive: 'visit', pastSimple: 'visited', pastParticiple: 'visited', translation: 'visitar', type: 'regular' },
  { infinitive: 'wait', pastSimple: 'waited', pastParticiple: 'waited', translation: 'esperar', type: 'regular' },
  { infinitive: 'walk', pastSimple: 'walked', pastParticiple: 'walked', translation: 'caminar', type: 'regular' },
  { infinitive: 'want', pastSimple: 'wanted', pastParticiple: 'wanted', translation: 'querer', type: 'regular' },
  { infinitive: 'wash', pastSimple: 'washed', pastParticiple: 'washed', translation: 'lavar', type: 'regular' },
  { infinitive: 'watch', pastSimple: 'watched', pastParticiple: 'watched', translation: 'ver', type: 'regular' },
  { infinitive: 'wish', pastSimple: 'wished', pastParticiple: 'wished', translation: 'desear', type: 'regular' },
  { infinitive: 'work', pastSimple: 'worked', pastParticiple: 'worked', translation: 'trabajar', type: 'regular' }
];
